#!/usr/bin/env python3
"""Generate/check paper statistics and capture release provenance (stdlib only)."""
import argparse
from collections import Counter
import json
from pathlib import Path
import re
import subprocess

import run

ROOT = Path(__file__).resolve().parent
KINDS = ('flatten_matrix_proof', 'degenerate_proof', 'forced_product_proof',
         'backtracking_proof', 'rank_one_span_proof')


def artifacts():
    result = {}
    for name in ('q02_n333', 'q03_n233'):
        cert = ROOT / 'certs/matrix' / run.RECIPES[name].certificate_name
        text = cert.read_text()
        counts = Counter(re.findall(r'^    (\w+_proof) \{', text, re.M))
        if set(counts) - set(KINDS) or sum(counts.values()) != text.count('constrained_tensors {'):
            raise ValueError(f'{cert}: missing or unknown proof records')
        result[name] = {
            'files': {str(p.relative_to(ROOT)): {'sha256': run.digest(p), 'bytes': p.stat().st_size}
                      for p in (cert, run.archive_path(cert))},
            'proof_counts': {k: counts[k] for k in KINDS},
            'commands': [f'python3 run.py {cmd} {name}' for cmd in
                         ('verify-cert', 'verify-table', 'profile')],
            'expected': {'certified_bound': run.RECIPES[name].rank,
                         'subspaces': run.RECIPES[name].records,
                         'covering_pairs': run.RECIPES[name].pairs,
                         'profiles': run.standard_expectation(run.RECIPES[name])['count'],
                         'jobs': run.standard_expectation(run.RECIPES[name])['jobs'],
                         'nodes': run.standard_expectation(run.RECIPES[name])['nodes']},
        }
    return result


def generated(data, *, include_paper=True):
    tex = '% Generated by python3 release.py --update; do not edit.\n'
    for name, prefix in [('q02_n333', 'Binary'), ('q03_n233', 'Ternary')]:
        for kind, label in zip(KINDS, ('Flatten', 'Degenerate', 'Forced', 'Backtracking', 'RankOneSpan')):
            tex += f'\\newcommand{{\\{prefix}{label}Count}}{{{data[name]["proof_counts"][kind]}}}\n'
    files = {'release/artifacts.json': json.dumps(data, indent=2, sort_keys=True) + '\n'}
    if include_paper:
        files['paper/proof_counts.tex'] = tex
    return files


def manifest(data, logs):
    """Retain original runner metadata/output; never infer a run from expectations."""
    evidence = []
    for path in logs:
        content = path.read_text()
        metadata = json.loads(content.splitlines()[0])
        statuses = re.findall(r'^runner_status=(PASS|FAIL) elapsed_seconds=', content, re.M)
        evidence.append({'log': str(path), 'sha256': run.digest(path),
                         'metadata': metadata, 'runner_status': statuses[-1] if statuses else 'INCOMPLETE',
                         'output': content})
    def git(*args):
        return subprocess.check_output(['git', *args], cwd=ROOT, text=True).strip()
    return {'schema_version': 1, 'code_commit': git('rev-parse', 'HEAD'),
            'worktree_dirty': bool(git('status', '--porcelain')),
            'artifacts': data, 'runs': evidence,
            'note': 'Expected summaries are reference data, not verification evidence. '
                    'Each run records its own commit and input hashes; inspect these before release.'}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--update', action='store_true', help='refresh tracked generated files')
    parser.add_argument('--manifest', type=Path, help='write a release attachment with current code commit')
    parser.add_argument('--log', type=Path, action='append', default=[], help='include an original run.py log')
    args = parser.parse_args()
    data = artifacts()
    # Public checkouts omit the paper; local paper checkouts still validate it.
    for filename, expected in generated(data, include_paper=(ROOT / 'paper').is_dir()).items():
        path = ROOT / filename
        if args.update:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(expected)
        elif not path.exists() or path.read_text() != expected:
            parser.error(f'{filename} is stale; run python3 release.py --update')
    if args.manifest:
        args.manifest.parent.mkdir(parents=True, exist_ok=True)
        args.manifest.write_text(json.dumps(manifest(data, args.log), indent=2, sort_keys=True) + '\n')
    print('Release artifact hashes and proof counts: OK')


if __name__ == '__main__':
    main()
