// Golden-file regression test for subspace_bounds/search/orbit_enumerator.h
// (the fast enumerator).
//
// The fast enumerator must emit byte-for-byte the same canonical certificate as
// the slow reference oracle, so it is checked against the SAME goldens under
// `subspace_bounds/search/testdata/orbit_enumerator/matrix_q<q>_n<N0><N1><N2>.pb.txt`.
// The goldens are regenerated by
// `//subspace_bounds/search:testdata_generator_main`.

#include "subspace_bounds/search/orbit_enumerator.h"

#include <string>

#include "google/protobuf/util/message_differencer.h"
#include "gtest/gtest.h"

#include "core/certificate.pb.h"
#include "core/proto_io.h"
#include "matrix/problem.h"

namespace {

template <class Problem> void CheckAgainstGolden() {
  const typename Problem::SymmetryGroup group;
  const OrbitEnumerator<Problem> enumerator(&group);
  pb::Certificate computed = enumerator.Search();

  const std::string path = "subspace_bounds/search/testdata/orbit_enumerator/" +
                           Problem::Name() + ".pb.txt";
  pb::Certificate golden = ReadProtoFromFile<pb::Certificate>(path);

  google::protobuf::util::MessageDifferencer diff;
  std::string report;
  diff.ReportDifferencesToString(&report);
  EXPECT_TRUE(diff.Compare(golden, computed)) << report;
}

TEST(OrbitEnumeratorTest, MatrixQ2) {
  CheckAgainstGolden<matrix::Problem<2, 1, 2, 3>>();
  CheckAgainstGolden<matrix::Problem<2, 1, 3, 2>>();
  CheckAgainstGolden<matrix::Problem<2, 2, 1, 3>>();
  CheckAgainstGolden<matrix::Problem<2, 2, 2, 2>>();
  CheckAgainstGolden<matrix::Problem<2, 2, 2, 3>>();
  CheckAgainstGolden<matrix::Problem<2, 2, 3, 1>>();
  CheckAgainstGolden<matrix::Problem<2, 2, 3, 2>>();
  CheckAgainstGolden<matrix::Problem<2, 2, 3, 3>>();
  CheckAgainstGolden<matrix::Problem<2, 3, 1, 2>>();
  CheckAgainstGolden<matrix::Problem<2, 3, 2, 1>>();
  CheckAgainstGolden<matrix::Problem<2, 3, 2, 2>>();
  CheckAgainstGolden<matrix::Problem<2, 3, 2, 3>>();
  CheckAgainstGolden<matrix::Problem<2, 3, 3, 2>>();
  CheckAgainstGolden<matrix::Problem<2, 3, 3, 3>>();
}

} // namespace
