// Golden-file regression test for subspace_bounds/search/rank_lower_bound_computer.h.
//
// For each matrix format we load the enumerator golden from
// subspace_bounds/search/testdata/orbit_enumerator/, then run ProcessOrbits three times in a
// chain (basic; basic+degenerate; all three techniques), comparing the
// certificate after each step to the matching golden under
// subspace_bounds/search/testdata/rank_lower_bound_{basic,basic_degenerate,all}/. The goldens
// are regenerated by //subspace_bounds/search:testdata_generator_main.

#include "subspace_bounds/search/rank_lower_bound_computer.h"

#include <string>

#include "google/protobuf/util/message_differencer.h"
#include "gtest/gtest.h"

#include "core/certificate.pb.h"
#include "core/proto_io.h"
#include "matrix/problem.h"

namespace {

void ExpectEqual(const pb::Certificate &golden,
                 const pb::Certificate &computed) {
  google::protobuf::util::MessageDifferencer diff;
  std::string report;
  diff.ReportDifferencesToString(&report);
  EXPECT_TRUE(diff.Compare(golden, computed)) << report;
}

template <class Problem> void CheckAgainstGolden() {
  const std::string filename = Problem::Name() + ".pb.txt";
  pb::Certificate cert = ReadProtoFromFile<pb::Certificate>(
      "subspace_bounds/search/testdata/orbit_enumerator/" + filename);

  ProcessOrbits<Problem>({.basic_method = true,
                          .degenerate_method = false,
                          .backtracking_step_limit = 0},
                         /*output_path=*/"", &cert);
  ExpectEqual(ReadProtoFromFile<pb::Certificate>(
                  "subspace_bounds/search/testdata/rank_lower_bound_basic/" + filename),
              cert);

  ProcessOrbits<Problem>({.basic_method = true,
                          .degenerate_method = true,
                          .backtracking_step_limit = 0},
                         /*output_path=*/"", &cert);
  ExpectEqual(
      ReadProtoFromFile<pb::Certificate>(
          "subspace_bounds/search/testdata/rank_lower_bound_basic_degenerate/" + filename),
      cert);

  ProcessOrbits<Problem>({.basic_method = true,
                          .degenerate_method = true,
                          .backtracking_step_limit = 100'000},
                         /*output_path=*/"", &cert);
  ExpectEqual(ReadProtoFromFile<pb::Certificate>(
                  "subspace_bounds/search/testdata/rank_lower_bound_all/" + filename),
              cert);
}

// only_orbits: recomputing one orbit from scratch, with the rest of the
// certificate pre-seeding the map, must reach the golden's bound for that
// orbit and leave every other orbit untouched. (The proof type may differ from
// the golden's because the golden was produced by a chain of passes in which
// forced product ran before degenerate.)
TEST(RankLowerBoundComputerTest, OnlyOrbitsRecomputesOneOrbit) {
  using Problem = matrix::Problem<2, 2, 2, 2>;
  const pb::Certificate golden = ReadProtoFromFile<pb::Certificate>(
      "subspace_bounds/search/testdata/rank_lower_bound_all/" + Problem::Name() + ".pb.txt");
  for (int k = 0; k < golden.constrained_tensors_size(); ++k) {
    pb::Certificate cert = golden;
    pb::ConstrainedTensor *rt = cert.mutable_constrained_tensors(k);
    rt->clear_rank_lower_bound();
    rt->clear_rank_lower_bound_proof();
    ProcessOrbits<Problem>({.basic_method = true,
                            .degenerate_method = true,
                            .backtracking_step_limit = 100'000,
                            .only_orbits = {static_cast<int>(rt->index())}},
                           /*output_path=*/"", &cert);
    for (int i = 0; i < golden.constrained_tensors_size(); ++i) {
      const pb::ConstrainedTensor &g = golden.constrained_tensors(i);
      const pb::ConstrainedTensor &c = cert.constrained_tensors(i);
      EXPECT_EQ(c.rank_lower_bound(), g.rank_lower_bound())
          << "orbit " << i << " after recomputing orbit " << k;
      if (i == k) {
        EXPECT_NE(c.rank_lower_bound_proof().proof_case(),
                  pb::RankLowerBoundProof::PROOF_NOT_SET);
      } else {
        google::protobuf::util::MessageDifferencer diff;
        EXPECT_TRUE(diff.Compare(g, c)) << "orbit " << i << " changed";
      }
    }
  }
}

TEST(RankLowerBoundComputerTest, MatrixQ2) {
  CheckAgainstGolden<matrix::Problem<2, 1, 2, 3>>();
  CheckAgainstGolden<matrix::Problem<2, 1, 3, 2>>();
  CheckAgainstGolden<matrix::Problem<2, 2, 1, 3>>();
  CheckAgainstGolden<matrix::Problem<2, 2, 2, 2>>();
  CheckAgainstGolden<matrix::Problem<2, 2, 2, 3>>();
  CheckAgainstGolden<matrix::Problem<2, 2, 3, 1>>();
  CheckAgainstGolden<matrix::Problem<2, 2, 3, 2>>();
  CheckAgainstGolden<matrix::Problem<2, 2, 3, 3>>();
  CheckAgainstGolden<matrix::Problem<2, 3, 1, 2>>();
  CheckAgainstGolden<matrix::Problem<2, 3, 2, 1>>();
  CheckAgainstGolden<matrix::Problem<2, 3, 2, 2>>();
  CheckAgainstGolden<matrix::Problem<2, 3, 2, 3>>();
}

} // namespace
